tags:
  - TODO
  - FIXME
  - BUG
  - NOTE
  - LOGGING
  - OLD_DEBUG

include:
  - "*.hpp"
  - "*.cpp"
  - "*.c"
  - "*.h"

exclude:
  - "m4/**"
  - "firmware-bin/**"

json: false
flat: false
no_color: false
