# Copyright (C) 2019 GSI Helmholtz Centre for Heavy Ion Research GmbH
#
# Build instructions for the saftlib project using Travis CI
#
# Author Enkhbold Ochirsuren <E.Ochirsuren@gsi.de>

language: cpp
os: linux
dist: xenial
sudo: required

compiler:
- gcc

# uncomment below list to build the given branches only
#branches:
#  only:
#  - master
#  - temp_sense
#  - travisci

# show CPU info, update package manager
before_install:
- lscpu
- nproc
- sudo apt-get update

# install required packages
#install:
- sudo apt-get install build-essential --install-suggests -y
- sudo apt-get install docbook-utils -y
- sudo apt-get install libreadline-dev -y
- sudo apt-get install zlib1g:i386 -y
- sudo apt-get install linux-headers-$(uname -r) -y
- sudo apt-get install sdcc fxload -y
- sudo apt-get install autotools-dev -y
- sudo apt-get install automake -y
- sudo apt-get install libtool -y
- sudo apt-get install libglibmm-2.4 -y
- sudo apt-get install libglib2.0 -y
- sudo apt-get install xsltproc -y

# saftlib depends on bel_projects
# - build bel_projects first (master branch only) and
# - build saftlib project (override built-in checkout by Travis)
before_script:
- git clone --recursive https://github.com/ebold/bel_projects.git
- cd bel_projects
- git checkout master
- ./fix-git.sh
- sed -i 's/spec_wb.o//g' ip_cores/fpga-config-space/pcie-wb/Makefile
- cd ip_cores/saftlib
- "if [ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]; then
    git fetch origin +refs/pull/$TRAVIS_PULL_REQUEST/merge:m_$TRAVIS_PULL_REQUEST &&
    git checkout -fq m_$TRAVIS_PULL_REQUEST;
  else
    git checkout $TRAVIS_BRANCH && git pull;
  fi"
- git log -n 5 --oneline
- cd ../..
- make etherbone
- make tools
- make driver
- sudo make install

# make and install saftlib
script:
- make saftlib -j$(nproc)

after_success:
- sudo make saftlib-install
