\input texinfo
@setfilename Types.info
@documentencoding us-ascii
@settitle Saftlib
@direntry
* Saftlib: (Types).   Types used in Saftlib interfaces.
@end direntry

@node Top
@top Saftlib
@chapheading Types

The saftlib interfaces documentation uses a number of types which are character encoded. Because Saftlib used DBus in the past, the encoding is similar but not identical to the DBus type encoding. The following table lists all types and their representation in the C++ API:

@example 
y        uint8_t
b        bool
n        int16_t
q        uint16_t
i        int32_t
u        uint32_t
x        int64_t
t        uint64_t
d        double
T        saftlib::Time
s        std::string
aX       std::vector<X> where X is can be any type
a@{KV@}    std::map<K,V> K and V are are key and value types

@bye
