name: CI Basic Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install missing packages
      run: sudo apt-get -y install automake libreadline-dev docbook-utils build-essential libboost-all-dev pkg-config libsigc++-2.0-dev xsltproc

    - name: Set PKG_CONFIG_PATH
      run: export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

    - name: Create symlinks
      run: sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: Clone and compile bel_projects
      run: |
        git clone https://github.com/GSI-CS-CO/bel_projects.git
        cd bel_projects
        git checkout fallout
        make
        make etherbone
        sudo make etherbone-install
        cd ..

    - name: Configure and compile saftlib and run saft-testbench
      run: |
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
        sudo saft-testbench
        sudo saft-testbench -p

    - name: Clean saftlib
      run: make clean

    - name: Test parallel compilation and run saft-testbench and build all examples
      run: |
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        sudo saft-testbench
        sudo saft-testbench -p
        pkg-config saftlib --cflags
        pkg-config saftlib --libs
        cd saftbus-gen
        ./autogen.sh
        ./configure
        make
        sudo make install
        cd ../examples/SimpleFirmware
        ./autogen.sh
        ./configure
        make
        cd ../../saftbus/examples/ex00
        ./autogen.sh
        ./configure
        make
        cd ../ex01_simple_dice
        ./autogen.sh
        ./configure
        make
        cd ../ex02_dice_cup/
        ./autogen.sh
        ./configure
        make
        cd ../../..

  doxygen:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: ./Doxyfile

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
